Lynn/create matching schema
CS3219-AY2425S1/cs3219-ay2425s1-project-g31 pull request #102
Opened 2024-10-11 15:21 UTC by lynnlow175

2024-10-11 16:03 UTC, Daviancold commented
Do note this satisfies #90 and not #89

2024-10-11 16:09 UTC, Daviancold commented on backend/matching-service/src/models/matching.model.ts
> +        default: Date.now,
Good use of unix epoch time

2024-10-11 16:09 UTC, Daviancold approved these changes
LGTM

2024-10-13 14:04 UTC, glemenneo requested changes
Should create some indexes to support more advanced queries. Based on the existing data table design, seems like need to support sorting by complexity and date. Should add an index for that, can refer to question schema for a reference. 

Can also refer to the index section of the mongoose guide for instructions on how to create indexes.
https://mongoosejs.com/docs/guide.html

2024-10-14 04:28 UTC, glemenneo approved these changes

2024-10-14 05:36 UTC, merged