CollabDB initialisation
CS3219-AY2425S1/cs3219-ay2425s1-project-g31 pull request #170
Opened 2024-10-28 06:25 UTC by Daviancold

2024-10-30 05:37 UTC, glemenneo requested changes

2024-10-30 05:37 UTC, glemenneo commented on backend/collaboration-service/src/controllers/collab.controller.ts
> +        const errorMessages = errors.map((error: ValidationError) => `INVALID_${error.property.toUpperCase()}`)
Can refer to my lastest pr for how to send back verbose error messages

2024-10-30 05:37 UTC, glemenneo commented on backend/collaboration-service/src/models/collab.model.ts
> +
Missing some indexes, will need for pagination

2024-10-31 16:23 UTC, shishirbychapur commented
> Pagination will be implemented subsequently by @yunruu

i thought session history is taken from matching db? why do we need pagination for collabDB?

2024-10-31 16:29 UTC, yunruu commented
> > Pagination will be implemented subsequently by @yunruu
> 
> i thought session history is taken from matching db? why do we need pagination for collabDB?

Yep session history retrieval is being done on matching service

2024-11-01 15:59 UTC, glemenneo approved these changes

2024-11-01 16:00 UTC, merged